import type { NavItem } from '@/types/menu';

/**
 * Static MES navigation tree.
 * This replaces DB-driven menu loading for the core MES feature set.
 * Builder tools (스키마/플로우/메뉴 빌더) are rendered separately in the sidebar.
 */
export const MES_NAV: NavItem[] = [
  {
    id: 'nav-master',
    parentId: null,
    label: '기준정보',
    icon: 'Database',
    displayOrder: 10,
    children: [
      {
        id: 'nav-items',
        parentId: 'nav-master',
        label: '품목관리',
        icon: 'Package',
        href: '/app/mes/items',
        displayOrder: 1,
        children: [],
      },
      {
        id: 'nav-bom',
        parentId: 'nav-master',
        label: 'BOM 관리',
        icon: 'GitBranch',
        href: '/app/mes/bom',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-work-centers',
        parentId: 'nav-master',
        label: '공정 관리',
        icon: 'Cog',
        href: '/app/mes/work-centers',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-routing',
        parentId: 'nav-master',
        label: '라우팅 관리',
        icon: 'Workflow',
        href: '/app/mes/routing',
        displayOrder: 30,
        children: [],
      },
      {
        id: 'nav-item-prices',
        parentId: 'nav-master',
        label: '단가관리',
        icon: 'CircleDollarSign',
        href: '/app/mes/item-prices',
        displayOrder: 40,
        children: [],
      },
    ],
  },
  {
    id: 'nav-purchase',
    parentId: null,
    label: '구매관리',
    icon: 'ShoppingCart',
    displayOrder: 15,
    children: [
      {
        id: 'nav-purchase-orders',
        parentId: 'nav-purchase',
        label: '발주관리',
        icon: 'FileInput',
        href: '/app/mes/purchase-orders',
        displayOrder: 10,
        children: [],
      },
    ],
  },
  {
    id: 'nav-production',
    parentId: null,
    label: '생산관리',
    icon: 'Factory',
    displayOrder: 20,
    children: [
      {
        id: 'nav-production-plan',
        parentId: 'nav-production',
        label: '생산계획 관리',
        icon: 'CalendarDays',
        href: '/app/mes/production-plan',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-mrp',
        parentId: 'nav-production',
        label: 'MRP 소요량',
        icon: 'Calculator',
        href: '/app/mes/mrp',
        displayOrder: 15,
        children: [],
      },
      {
        id: 'nav-work-orders',
        parentId: 'nav-production',
        label: '작업지시 관리',
        icon: 'ClipboardList',
        href: '/app/mes/work-orders',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-production-results',
        parentId: 'nav-production',
        label: '작업실적 관리',
        icon: 'BarChart2',
        href: '/app/mes/production-results',
        displayOrder: 30,
        children: [],
      },
      {
        id: 'nav-process-progress',
        parentId: 'nav-production',
        label: '공정진행 관리',
        icon: 'Activity',
        href: '/app/mes/process-progress',
        displayOrder: 40,
        children: [],
      },
      {
        id: 'nav-rework',
        parentId: 'nav-production',
        label: '재작업/보류 관리',
        icon: 'RefreshCw',
        href: '/app/mes/rework',
        displayOrder: 50,
        children: [],
      },
      {
        id: 'nav-outsourcing',
        parentId: 'nav-production',
        label: '외주공정 관리',
        icon: 'Truck',
        href: '/app/mes/outsourcing',
        displayOrder: 60,
        children: [],
      },
    ],
  },
  {
    id: 'nav-sales',
    parentId: null,
    label: '영업관리',
    icon: 'TrendingUp',
    displayOrder: 25,
    children: [
      {
        id: 'nav-quotations',
        parentId: 'nav-sales',
        label: '견적관리',
        icon: 'FileText',
        href: '/app/mes/quotations',
        displayOrder: 5,
        children: [],
      },
      {
        id: 'nav-sales-orders',
        parentId: 'nav-sales',
        label: '수주관리',
        icon: 'ClipboardList',
        href: '/app/mes/sales-orders',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-shipments',
        parentId: 'nav-sales',
        label: '출하관리',
        icon: 'Truck',
        href: '/app/mes/shipments',
        displayOrder: 20,
        children: [],
      },
    ],
  },
  {
    id: 'nav-field',
    parentId: null,
    label: '현장수집',
    icon: 'Tablet',
    displayOrder: 30,
    children: [
      {
        id: 'nav-pop',
        parentId: 'nav-field',
        label: 'POP/태블릿 입력',
        icon: 'MonitorSmartphone',
        href: '/app/mes/pop',
        displayOrder: 10,
        children: [],
      },
    ],
  },
  {
    id: 'nav-quality',
    parentId: null,
    label: '품질관리',
    icon: 'ShieldCheck',
    displayOrder: 40,
    children: [
      {
        id: 'nav-inspection',
        parentId: 'nav-quality',
        label: '공정검사',
        icon: 'ClipboardCheck',
        href: '/app/mes/inspection',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-defects',
        parentId: 'nav-quality',
        label: '불량관리',
        icon: 'AlertTriangle',
        href: '/app/mes/defects',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-spc',
        parentId: 'nav-quality',
        label: 'SPC/통계분석',
        icon: 'TrendingUp',
        href: '/app/mes/spc',
        displayOrder: 30,
        children: [],
      },
      {
        id: 'nav-measurement',
        parentId: 'nav-quality',
        label: '측정기 연동',
        icon: 'Ruler',
        href: '/app/mes/measurement',
        displayOrder: 40,
        children: [],
      },
    ],
  },
  {
    id: 'nav-material',
    parentId: null,
    label: '자재/재고',
    icon: 'Package',
    displayOrder: 50,
    children: [
      {
        id: 'nav-material-receipt',
        parentId: 'nav-material',
        label: '자재입고 관리',
        icon: 'PackagePlus',
        href: '/app/mes/material-receipt',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-lot',
        parentId: 'nav-material',
        label: 'LOT/Serial 관리',
        icon: 'Tag',
        href: '/app/mes/lot',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-inventory',
        parentId: 'nav-material',
        label: '재고현황',
        icon: 'Boxes',
        href: '/app/mes/inventory',
        displayOrder: 30,
        children: [],
      },
      {
        id: 'nav-inventory-transactions',
        parentId: 'nav-material',
        label: '입출고 관리',
        icon: 'ArrowLeftRight',
        href: '/app/mes/inventory-transactions',
        displayOrder: 40,
        children: [],
      },
    ],
  },
  {
    id: 'nav-traceability',
    parentId: null,
    label: '추적성',
    icon: 'Search',
    displayOrder: 60,
    children: [
      {
        id: 'nav-traceability-lot',
        parentId: 'nav-traceability',
        label: 'LOT Traceability',
        icon: 'Network',
        href: '/app/mes/traceability',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-trace-reverse',
        parentId: 'nav-traceability',
        label: '역추적/정추적',
        icon: 'ArrowLeftRight',
        href: '/app/mes/trace-reverse',
        displayOrder: 20,
        children: [],
      },
    ],
  },
  {
    id: 'nav-monitoring',
    parentId: null,
    label: '모니터링',
    icon: 'Monitor',
    displayOrder: 70,
    children: [
      {
        id: 'nav-dashboard',
        parentId: 'nav-monitoring',
        label: '생산현황 대시보드',
        icon: 'LayoutDashboard',
        href: '/app/mes/dashboard',
        displayOrder: 10,
        children: [],
      },
    ],
  },
  {
    id: 'nav-analytics',
    parentId: null,
    label: '분석/보고',
    icon: 'FileBarChart',
    displayOrder: 80,
    children: [
      {
        id: 'nav-lot-history',
        parentId: 'nav-analytics',
        label: 'LOT 이력 조회',
        icon: 'History',
        href: '/app/mes/lot-history',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-costing',
        parentId: 'nav-analytics',
        label: '원가분석',
        icon: 'Calculator',
        href: '/app/mes/costing',
        displayOrder: 20,
        children: [],
      },
    ],
  },
  {
    id: 'nav-sysadmin',
    parentId: null,
    label: '시스템관리',
    icon: 'Settings',
    displayOrder: 90,
    children: [
      {
        id: 'nav-users',
        parentId: 'nav-sysadmin',
        label: '사용자/권한 관리',
        icon: 'Users',
        href: '/app/mes/users',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-common-codes',
        parentId: 'nav-sysadmin',
        label: '공통코드 관리',
        icon: 'BookOpen',
        href: '/app/mes/common-codes',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-features',
        parentId: 'nav-sysadmin',
        label: '기능 관리',
        icon: 'Puzzle',
        href: '/app/mes/features',
        displayOrder: 5,
        children: [],
      },
      {
        id: 'nav-lot-rules',
        parentId: 'nav-sysadmin',
        label: 'LOT 규칙',
        icon: 'Fingerprint',
        href: '/app/mes/lot-rules',
        displayOrder: 30,
        children: [],
      },
    ],
  },
  {
    id: 'nav-equipment-integration',
    parentId: null,
    label: '설비연동',
    icon: 'Cpu',
    displayOrder: 95,
    children: [
      {
        id: 'nav-gateways',
        parentId: 'nav-equipment-integration',
        label: 'Edge Gateway',
        icon: 'Wifi',
        href: '/app/mes/gateways',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-equipment-connections',
        parentId: 'nav-equipment-integration',
        label: '설비 연결 설정',
        icon: 'Cable',
        href: '/app/mes/equipment-connections',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-tags',
        parentId: 'nav-equipment-integration',
        label: '태그 사전',
        icon: 'Tag',
        href: '/app/mes/tags',
        displayOrder: 30,
        children: [],
      },
    ],
  },
  {
    id: 'nav-integration',
    parentId: null,
    label: '시스템연계',
    icon: 'Link2',
    displayOrder: 100,
    children: [
      {
        id: 'nav-erp',
        parentId: 'nav-integration',
        label: 'ERP 연계',
        icon: 'Building2',
        href: '/app/mes/erp',
        displayOrder: 10,
        children: [],
      },
      {
        id: 'nav-approval',
        parentId: 'nav-integration',
        label: '전자결재/그룹웨어 연계',
        icon: 'FileCheck',
        href: '/app/mes/approval',
        displayOrder: 20,
        children: [],
      },
      {
        id: 'nav-wms',
        parentId: 'nav-integration',
        label: 'WMS/SCM 연계',
        icon: 'Boxes',
        href: '/app/mes/wms',
        displayOrder: 30,
        children: [],
      },
    ],
  },
];
