INSERT INTO "profiles" ("id", "email", "name", "role", "updated_at") VALUES ('system-seed-user', 'system@mes.internal', 'System', 'ADMIN', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "menus" ("id", "name", "icon", "menu_type", "display_order", "created_by", "updated_at") VALUES ('menu-master-data', '기준정보', 'Database', 'FOLDER', 0, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "schemas" ("id", "name", "description", "icon", "color", "fields", "is_template", "display_order", "created_by", "updated_at") VALUES ('template-schema-0', '거래처', '공급업체, 고객사 등 거래처 정보', 'Building2', '#6366f1', '[{"id":"f1","name":"거래처코드","key":"code","type":"text","required":true,"unique":true,"displayOrder":0},{"id":"f2","name":"거래처명","key":"name","type":"text","required":true,"unique":false,"displayOrder":1},{"id":"f3","name":"거래처유형","key":"type","type":"select","required":true,"unique":false,"options":["공급업체","고객사","내부"],"displayOrder":2},{"id":"f4","name":"담당자","key":"contact_person","type":"text","required":false,"unique":false,"displayOrder":3},{"id":"f5","name":"연락처","key":"phone","type":"text","required":false,"unique":false,"displayOrder":4},{"id":"f6","name":"사용여부","key":"is_active","type":"boolean","required":false,"unique":false,"displayOrder":5}]', true, 0, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "menus" ("id", "parent_id", "name", "icon", "menu_type", "schema_id", "display_order", "created_by", "updated_at") VALUES ('menu-schema-0', 'menu-master-data', '거래처', 'Table', 'SCHEMA', 'template-schema-0', 0, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "schemas" ("id", "name", "description", "icon", "color", "fields", "is_template", "display_order", "created_by", "updated_at") VALUES ('template-schema-1', '품목', '원자재, 반제품, 완제품 등 품목 마스터', 'Package', '#8b5cf6', '[{"id":"f1","name":"품목코드","key":"code","type":"text","required":true,"unique":true,"displayOrder":0},{"id":"f2","name":"품목명","key":"name","type":"text","required":true,"unique":false,"displayOrder":1},{"id":"f3","name":"품목유형","key":"type","type":"select","required":true,"unique":false,"options":["원자재","반제품","완제품","소모품"],"displayOrder":2},{"id":"f4","name":"단위","key":"unit","type":"select","required":true,"unique":false,"options":["EA","KG","M","L","BOX","SET"],"displayOrder":3},{"id":"f5","name":"단가","key":"unit_price","type":"number","required":false,"unique":false,"displayOrder":4},{"id":"f6","name":"안전재고","key":"safety_stock","type":"number","required":false,"unique":false,"displayOrder":5},{"id":"f7","name":"사용여부","key":"is_active","type":"boolean","required":false,"unique":false,"displayOrder":6}]', true, 1, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "menus" ("id", "parent_id", "name", "icon", "menu_type", "schema_id", "display_order", "created_by", "updated_at") VALUES ('menu-schema-1', 'menu-master-data', '품목', 'Table', 'SCHEMA', 'template-schema-1', 1, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "schemas" ("id", "name", "description", "icon", "color", "fields", "is_template", "display_order", "created_by", "updated_at") VALUES ('template-schema-2', '공정', '생산 공정 마스터', 'GitBranch', '#10b981', '[{"id":"f1","name":"공정코드","key":"code","type":"text","required":true,"unique":true,"displayOrder":0},{"id":"f2","name":"공정명","key":"name","type":"text","required":true,"unique":false,"displayOrder":1},{"id":"f3","name":"공정유형","key":"type","type":"select","required":false,"unique":false,"options":["기계가공","조립","검사","포장","외주"],"displayOrder":2},{"id":"f4","name":"표준작업시간(분)","key":"std_time_min","type":"number","required":false,"unique":false,"displayOrder":3}]', true, 2, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "menus" ("id", "parent_id", "name", "icon", "menu_type", "schema_id", "display_order", "created_by", "updated_at") VALUES ('menu-schema-2', 'menu-master-data', '공정', 'Table', 'SCHEMA', 'template-schema-2', 2, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "schemas" ("id", "name", "description", "icon", "color", "fields", "is_template", "display_order", "created_by", "updated_at") VALUES ('template-schema-3', '설비', '생산 설비 및 기계 마스터', 'Cog', '#f59e0b', '[{"id":"f1","name":"설비코드","key":"code","type":"text","required":true,"unique":true,"displayOrder":0},{"id":"f2","name":"설비명","key":"name","type":"text","required":true,"unique":false,"displayOrder":1},{"id":"f3","name":"설비유형","key":"type","type":"select","required":false,"unique":false,"options":["CNC","프레스","용접기","검사장비","조립라인"],"displayOrder":2},{"id":"f4","name":"제조사","key":"manufacturer","type":"text","required":false,"unique":false,"displayOrder":3},{"id":"f5","name":"설치일","key":"install_date","type":"date","required":false,"unique":false,"displayOrder":4},{"id":"f6","name":"가동여부","key":"is_active","type":"boolean","required":false,"unique":false,"displayOrder":5}]', true, 3, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "menus" ("id", "parent_id", "name", "icon", "menu_type", "schema_id", "display_order", "created_by", "updated_at") VALUES ('menu-schema-3', 'menu-master-data', '설비', 'Table', 'SCHEMA', 'template-schema-3', 3, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "schemas" ("id", "name", "description", "icon", "color", "fields", "is_template", "display_order", "created_by", "updated_at") VALUES ('template-schema-4', '공통코드', '시스템 공통 분류 코드', 'List', '#ef4444', '[{"id":"f1","name":"그룹코드","key":"group_code","type":"text","required":true,"unique":false,"displayOrder":0},{"id":"f2","name":"그룹명","key":"group_name","type":"text","required":true,"unique":false,"displayOrder":1},{"id":"f3","name":"코드","key":"code","type":"text","required":true,"unique":false,"displayOrder":2},{"id":"f4","name":"코드명","key":"code_name","type":"text","required":true,"unique":false,"displayOrder":3},{"id":"f5","name":"정렬순서","key":"sort_order","type":"number","required":false,"unique":false,"displayOrder":4},{"id":"f6","name":"사용여부","key":"is_active","type":"boolean","required":false,"unique":false,"displayOrder":5}]', true, 4, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "menus" ("id", "parent_id", "name", "icon", "menu_type", "schema_id", "display_order", "created_by", "updated_at") VALUES ('menu-schema-4', 'menu-master-data', '공통코드', 'Table', 'SCHEMA', 'template-schema-4', 4, 'system-seed-user', NOW()) ON CONFLICT ("id") DO NOTHING;
